apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scale-down-app
  namespace: secured-router-project
spec:
  schedule: '*/2 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scale-down-app
              image: registry.redhat.io/openshift4/ose-cli
              args:
                - /bin/sh
                - '-c'
                -  export HOME=/tmp && oc login https://api.cluster-12d8.sandbox786.opentlc.com:6443 --insecure-skip-tls-verify -u joel -p senha && oc scale --replicas=0 deployment java-sample -n secured-router-project 
              restartPolicy: OnFailure
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
